#!/bin/bash

if [[ $# -ne 1 ]]; then
    echo "usage: cinit <name>"
    exit 1
fi

echo "creating project \"$1\""

project=$1

# create the project if not initializing the current one
if [[ -ne "$project" "." ]]; then
    if [[ -d $project ]]; then
        echo "cinit : project \"$project\" already exists"
        exit 1
    fi

    mkdir $project
    cd $project
fi

mkdir src
mkdir include
mkdir tests

# create the project makefile
cat > makefile << _EOF_
SOURCES=\$(wildcard src/*.c)
OBJECTS=\$(SOURCES:.c=.o)
CFLAGS=-Wall -Wextra -Werror -Wno-unused-function -std=gnu99 -I./include/
EXE=$project

HAS_CCACHE := \$(shell command -v ccache 2> /dev/null)
ifdef HAS_CCACHE
    CC:=ccache \$(CC)
endif

all: \$(EXE)

\$(EXE) : \$(OBJECTS)
	\$(CC) -o \$@ $^ \$(LIBS) \$(CFLAGS)

run:
	./\$(EXE)

clean:
	\$(RM) \$(EXE)
	\$(RM) \$(OBJECTS)

.PHONY: run clean
_EOF_

# create default main file
cat > src/main.c << _EOF_
#include<stdio.h>

int main()
{
    puts("edit src/main.c to begin your project");
    return EXIT_SUCCESS;
}
_EOF_
